version: "3.9"
services:

 app:
   build: .
   container_name: app
   volumes:
    - "./:/work"
   working_dir: "/work"
   ports:
      - 7800:7800

 ui:
    build:
      context: ./ui
      target: dev
    volumes:
      - ./ui/:/ui
      - /ui/node_modules
      - /ui/.next
    command: npm run dev
    ports:
      - "5100:5100"
    environment:
      NODE_ENV: development

 ssh:
   build: 
      context: .
      dockerfile: Dockerfile_ssh
   container_name: ssh


#  mysql:
#    container_name: db
#    image: mysql:8.0
#    command: --default-authentication-plugin=mysql_native_password
#    environment:
#       MYSQL_DATABASE: db
#       MYSQL_ROOT_PASSWORD: example
#       MYSQL_USER: db
#       MYSQL_PASSWORD: example
 postgre:
    container_name: db
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: db
      POSTGRES_DB: db
